### ISSUE TITLE
`get_pyarrow_schema` fails when a Field is an Enum 

### ISSUE THREAD

**Issue by AbelThorne** [simw/pydantic-to-pyarrow#11]
```
class MyEnum(str, Enum):
    A = "A"
    B = "B"

class MyModel(BaseModel):
    event_type: MyEnum 
 
pa_schema = get_pyarrow_schema(MyModel)
``` 

this fails with `pydantic_to_pyarrow.schema.SchemaCreationError: Unknown type: <enum 'MyEnum'>`

**Comment by simw** [comment]
Thank you for the comment! The latest version (v0.1.2) should now work with the example above, converting the enum to a pa.dictionary type.
